steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/research-canvas:$_COMMIT_SHA'
      - '.'

  # Step 2: Push image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/research-canvas:$_COMMIT_SHA'

  # Step 3: Deploy to Cloud Run (Singapore)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'research-canvas'
      - '--image=gcr.io/$PROJECT_ID/research-canvas:$_COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'

images:
  - 'gcr.io/$PROJECT_ID/research-canvas:$_COMMIT_SHA'

substitutions:
  _COMMIT_SHA: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
