/**
 * 大分类 → 小分类映射（仅用于 UI 分组显示，不入库）
 * 小分类名称必须与 workspace.name 一致
 */
export interface IndustryCategory {
  label: string;
  icon: string;
  subCategories: string[];
}

export const INDUSTRY_CATEGORY_MAP: IndustryCategory[] = [
  { label: '农业', icon: '🌾', subCategories: ['农用机械'] },
  {
    label: '工业', icon: '🏭', subCategories: [
      '五金工具', '军工', '卡车', '基建地产链条',
      '工程机械/矿山机械', '机器人/工业自动化', '泛工业',
      '自动驾驶', '航空航天', '钠电', '锂电', '零部件',
    ],
  },
  { label: '建设', icon: '🏗️', subCategories: ['EPC', '设备租赁'] },
  { label: '消费', icon: '🛒', subCategories: ['两轮车/全地形车', '创新消费品', '报废车', '汽车'] },
  { label: '物流和运输', icon: '🚢', subCategories: ['车运/货代', '造船'] },
  {
    label: '电力', icon: '⚡', subCategories: [
      'bitcoin miner', '天然气发电', '核电', '电力运营商', '电网设备', '风光储',
    ],
  },
  { label: '科技和互联网', icon: '💻', subCategories: ['互联网/大模型', '工业软件', '数据中心设备'] },
  { label: '能源', icon: '🛢️', subCategories: ['LNG'] },
  { label: '资源', icon: '⛏️', subCategories: ['战略金属', '稀土', '铜金', '铝'] },
  { label: '政治', icon: '🏛️', subCategories: ['宏观'] },
];

/**
 * 小分类 → 公司名称列表
 * 用于迁移脚本创建公司文件夹
 */
export const INDUSTRY_COMPANIES: Record<string, string[]> = {
  '农用机械': [
    'Deere & Company',
    'Sandhills Global',
  ],
  '五金工具': [
    '杭州巨星科技股份有限公司',
    '创科实业有限公司',
  ],
  '军工': [
    'Mitsubishi Heavy Industries Ltd',
    'Bharat Electronics Ltd.',
    'CACI International Inc.',
    'Lockheed Martin Corp',
    'Northrop Grumman Corp',
    'Arc Media',
  ],
  '卡车': [
    '中国重汽',
    '中国重汽(香港)有限公司',
    'BLR Logistics (India) Limited',
    '徐工汽车',
  ],
  '基建地产链条': [
    'ConstructConnect',
    'Shimizu Corp.',
    'BHP Group Ltd',
    'Louisiana-Pacific Corporation',
    'SRM Concrete',
  ],
  '工程机械/矿山机械': [
    '中联重科',
    '徐工机械',
    '山推工程机械股份有限公司',
    '耐普矿机股份有限公司',
    '三一重工',
    '山东临工',
    '恒立液压',
    'Caterpillar Inc.',
    'Sandvik AB',
  ],
  '机器人/工业自动化': [
    '三花智控',
    '双环传动',
    '德昌电机控股',
    '汇川技术',
    '震裕科技',
    '拓普集团',
    '杰克缝纫机股份有限公司',
    'SMC Corp.',
    'Yaskawa',
    'KEYENCE ORD',
    'Kawasaki',
    '优必选',
    'Honeywell International Inc.',
    'Neuralink Corporation',
    '强脑科技',
    '微亿智造',
    '梅卡曼德机器人',
    '灵犀巧手',
    'ROCKWELL AUTOMAT ORD',
    'Schaeffler AG',
    'TESLA ORD',
    '巨生智能',
  ],
  '泛工业': [
    'D',
    '英科医疗',
  ],
  '自动驾驶': [
    '地平线',
    'NVIDIA Corp',
    'Kodiak Robotics',
    'テクノシステムリサーチ',
    '九识智能',
    '小马智行',
    '希迪智驾',
    'TESLA ORD',
    'WERIDE-W ORD',
  ],
  '航空航天': [
    'The Boeing Company',
    'EHang Holdings Ltd.',
    'Fortress Transportation and Infrastructure Investors LLC',
    'GE Aerospace',
    'Howmet Aerospace Inc.',
    'MTU Aero Engines AG',
    'Precision Castparts Corp.',
    'SpaceX',
    'Starlink',
    '宝武特钢集团有限公司',
    '宝钢特钢有限公司',
    '蓝箭航天',
    'RTX Corp',
  ],
  '钠电': [
    '上海普利特复合材料股份有限公司',
    '鹏辉能源',
    '宁德时代',
    '中创新航',
    '维科技术',
  ],
  '锂电': [
    '天津滨海能源发展股份有限公司',
    '杭州巨星科技股份有限公司',
    '亿纬锂能',
    '宁德时代',
    '上海璞泰来新能源科技股份有限公司',
    '容百科技',
  ],
  '零部件': [
    '宏发股份',
  ],
  'EPC': [
    'Taisei Corp',
    '大林組',
    'Nishimatsu Construction Co Ltd',
    '新日本空調株式会社',
    'Comfort Systems USA',
    'Quanta Services Inc.',
    'コムシスホールディングス',
  ],
  '设备租赁': [
    'Equipment Share',
  ],
  '宏观': [
    'Bank of America Corporation',
  ],
  '有色金属': [
    '厦门钨业股份有限公司',
  ],
  '未归类': [
    'Oracle',
  ],
  '金属与矿业': [
    'SMM (上海有色网)',
  ],
  '两轮车/全地形车': [
    '雅迪',
    '浙江涛涛车业股份有限公司',
    '涛涛车业',
    '春风动力',
    '九号公司',
    'Polaris Inc',
    'Skillsoft Corp',
  ],
  '创新消费品': [
    '安克创新',
  ],
  '报废车': [
    'COPART ORD',
  ],
  '汽车': [
    '比亚迪股份有限公司',
    'HYUNDAI MOTOR ORD',
    'Geely Automobile Holdings Ltd.',
    '宁德时代',
    '零跑汽车',
    '奇瑞汽车',
    'MARUTI SUZUKI INDIA ORD',
    'NIO-SW ORD',
  ],
  '车运/货代': [
    'C.H. Robinson Worldwide Inc.',
    'J.B. Hunt Transport Services Inc',
    'LANDSTAR SYSTEM ORD',
    'Ryder System Inc',
  ],
  '造船': [
    'HD HYUNDAI ELECTRIC ORD',
  ],
  'bitcoin miner': [
    'IREN ORD',
  ],
  '天然气发电': [
    '潍柴动力',
    '杰瑞股份',
    '西子洁能',
    '东方电气股份有限公司',
    '上海电气',
    '应流集团股份有限公司',
    '三菱重工業株式会社',
    'BLOOM ENERGY CL A ORD',
    '卡特彼勒',
    'SIEMENS ENERGY N ORD',
    'Fortress Transportation and Infrastructure Investors LLC',
    'GE VERNOVA',
    'Enchanted Rock',
    '杭汽轮',
  ],
  '核电': [
    'Sprott',
    '天工国际',
    'CAMECO ORD',
    'Cameco Corp',
    'KAZATOMPROM NAC ORD',
    'MIRION TECHNOLOGIES CL A ORD',
    'Commonwealth Fusion Systems',
    'DeepFission',
    'Tennessee Valley Authority',
    '电力公司',
  ],
  '电力运营商': [
    '龙源电力',
    '中国能源建设股份有限公司',
    '华能国际电力股份有限公司',
    '国电电力',
    'China Resources Power Holdings Co Ltd',
    'A2A S.p.A.',
    'ARGAN ORD',
    'Dominion Energy',
    'EDP - Energias de Portugal SA',
    'Elia Group',
    'Exelon Corporation',
    'Microsoft Corp',
    'National Grid plc',
    'Austrian Power Grid AG',
    'McKinsey & Company',
    'PJM Interconnection',
    'Tennessee Valley Authority',
    'chess',
    '中国南方电网有限责任公司',
    '国家电网',
    '西安风平能源科技有限公司',
    '达宝智能',
    'RWE AG',
    '电力公司',
  ],
  '电网设备': [
    'National grid',
    'Red Electrica',
    '思源电气',
    'HD HYUNDAI ELECTRIC ORD',
    'Powell Industries Inc.',
    'Commercial Cash',
    'MR',
    '江苏华鹏变压器有限公司',
  ],
  '风光储': [
    '京东方科技集团股份有限公司',
    '金风科技',
    'L&F',
    '宁德时代',
    '迈为股份',
    '德业股份',
    '晶科能源股份有限公司',
    '固德威',
    'Acciona Energía SA',
    'Canadian Solar Inc',
    'Canadian Solar Inc.',
    'Ceres Power Holdings plc',
    'FIRST SOLAR ORD',
    'First Solar',
    '中国长江三峡集团有限公司',
    '发电集团',
    '国家电网',
    '欣界能源',
    '华电新能源',
  ],
  '互联网/大模型': [
    'Tencent Holdings Ltd.',
    'Amazon.com Inc',
    'Alphabet Inc.',
    'Microsoft Corp.',
    'NVIDIA Corp',
    'Anthropic',
    'MiniMax',
    'OpenAI',
    '华为',
    '字节跳动',
    'ZoomInfo Technologies Inc.',
  ],
  '工业软件': [
    'Adobe Inc',
  ],
  '数据中心设备': [
    'UBS',
    '潍柴动力',
    '科士达',
    '英维克',
    '深圳市欧陆通电子股份有限公司',
    '北京四方继保自动化股份有限公司',
    '万国数据控股有限公司',
    'BLOOM ENERGY CL A ORD',
    'CBRE Group Inc',
    'DigitalBridge Group Inc',
    'Eaton Corp PLC',
    'Liberty Energy Inc',
    'Marathon Digital Holdings Inc',
    'NVIDIA Corp',
    'NVIDIA Corporation',
    'Blue Owl Digital Infrastructure',
    'Sightline Research',
    'Schneider Electric SE',
    'Vertiv Holdings Co',
  ],
  'LNG': [
    'Baker Hughes Company',
    'EQT Corporation',
  ],
  '战略金属': [
    '赛恩斯',
    '厦门钨业股份有限公司',
  ],
  '稀土': [
    '中国稀土控股',
    'Lynas Rare Earths Ltd',
    'MP MATERIALS CL A ORD',
    'Neo Performance Materials Inc',
  ],
  '铜金': [
    '紫金矿业集团股份有限公司',
    'First Quantum Minerals Ltd.',
  ],
  '铝': [
    '中国铝业股份有限公司',
    'Qatar Aluminium',
  ],
};

/** 每个小分类下需要创建的特殊子文件夹 */
export const INDUSTRY_SPECIAL_FOLDERS = ['行业研究', 'Expert', 'Sellside'];
